/**
 * Management of trading bots
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Модель ErrorResponse используется для представления ошибок API. Она включает следующие поля: - error: строка ошибки - detail: дополнительная информация об ошибке (опционально) - message: сообщение с подробным описанием ошибки (опционально)
 */
export interface ErrorResponse { 
    error: string;
    detail: string | null;
    message: string;
}

