/**
 * Management of trading bots
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Модель для ответа с флагом \"ok\" и деталями.  Attributes:     - ok: флаг успешности операции.     - details: дополнительные детали ответа.
 */
export interface OkOut { 
    ok?: boolean;
    details?: Array<any>;
}

